const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const E=require('../js/engine.js'),AI=require('../js/ai.js'),D=require('../js/data.js');
let passed=0;function test(name,f){f();passed++;console.log('✓ '+name);}
const game=n=>E.create(Array.from({length:n||2},(_,i)=>({name:'P'+i,ai:true})),123);
function give(s,c,n){s.players[s.current].tokens[c]+=n;s.bank[c]-=n;}
function grant(s,id){for(const l of [1,2,3])for(const field of ['market','decks']){const a=s[field][l],i=a.indexOf(id);if(i>=0)a.splice(i,1);}s.players[s.current].owned.push(id);}
test('90 physical card records, balanced levels/colors, 10 unique nobles, all local images',()=>{
 assert.equal(D.cards.length,90);assert.equal(D.nobles.length,10);assert.equal(new Set(D.nobles.map(n=>JSON.stringify(Object.entries(n.cost).sort()))).size,10);
 for(const l of [1,2,3])for(const c of E.COLORS)assert.equal(D.cards.filter(x=>x.level===l&&x.bonus===c).length,[0,8,6,4][l]);
 for(const c of D.cards)assert.ok(fs.statSync(path.join(__dirname,'..',c.image)).size>1000);
 assert.deepEqual(E.cards['white-L1-05'].cost,{white:3,blue:1,black:1});
});
test('Setup 2–4 players, independent deterministic shuffle and token supply',()=>{for(const n of [2,3,4]){const s=game(n);assert.equal(s.nobles.length,n+1);assert.equal(s.bank.white,[0,0,4,5,7][n]);assert.equal(s.bank.gold,5);assert.equal(s.market[1].length,4);assert.equal(s.decks[1].length,36);E.validate(s);}assert.deepEqual(game(),game());});
test('Take tokens, reject gold, invalid double, overdraw, negatives; input unchanged',()=>{const s=game(),original=E.clone(s),n=E.apply(s,{type:'take',tokens:{red:2}});assert.equal(n.players[0].tokens.red,2);assert.equal(n.current,1);assert.deepEqual(s,original);assert.throws(()=>E.apply(n,{type:'take',tokens:{red:2}}));for(const t of [{gold:1},{blue:3},{red:-1},{red:1,green:1,white:1,blue:1},{evil:1}])assert.throws(()=>E.apply(s,{type:'take',tokens:t}));assert.throws(()=>E.apply(s,{type:'take',tokens:{blue:1}})); const low=game();low.bank.red=low.bank.green=low.bank.black=0;assert.equal(E.apply(low,{type:'take',tokens:{blue:1,white:1}}).players[0].tokens.blue,1);});
test('Face-up and blind reservation replenish market; max three; no gold still allowed',()=>{let s=game(),id=s.market[1][0],n=E.apply(s,{type:'reserve',id});assert.equal(n.players[0].reserved[0],id);assert.equal(n.players[0].tokens.gold,1);assert.equal(n.market[1].length,4);assert.equal(n.decks[1].length,35);n=E.apply(s,{type:'reserve',level:3});assert.equal(n.players[0].reserved[0],s.decks[3].at(-1));assert.equal(n.market[3].length,4);s.bank.gold=0;assert.equal(E.apply(s,{type:'reserve',level:1}).players[0].tokens.gold,0);s.players[0].reserved=['a','b','c'];assert.throws(()=>E.apply(s,{type:'reserve',level:1}));});
test('Buy with discounts and optional gold; no overpay; reserved-card ownership enforced',()=>{let s=game();const id=s.market[1][0];for(const c of E.COLORS)give(s,c,Math.min(s.bank[c],E.cards[id].cost[c]||0));give(s,'gold',2);const pay=E.payment(s.players[0],id);assert.ok(pay);const color=E.COLORS.find(c=>pay[c]>0);pay[color]--;pay.gold++;const n=E.apply(s,{type:'buy',id,payment:pay});assert.ok(n.players[0].owned.includes(id));assert.equal(E.bonuses(n.players[0])[E.cards[id].bonus],1);E.validate(n);assert.throws(()=>E.apply(s,{type:'buy',id,payment:{gold:99}}));let r=E.apply(game(),{type:'reserve',level:1});assert.throws(()=>E.apply(r,{type:'buy',id:r.players[0].reserved[0]}));});
test('Overflow requires exact choice, allows newly acquired gold return',()=>{let s=game();give(s,'white',4);give(s,'blue',4);give(s,'red',2);s=E.apply(s,{type:'reserve',level:1});assert.equal(s.phase,'return');assert.equal(s.current,0);assert.throws(()=>E.apply(s,{type:'return',tokens:{gold:0}}));assert.throws(()=>E.apply(s,{type:'buy',id:s.market[1][0]}));s=E.apply(s,{type:'return',tokens:{gold:1}});assert.equal(s.current,1);assert.equal(E.sum(s.players[0].tokens),10);E.validate(s);});
test('Nobles use permanent cards, multiple candidates require one choice',()=>{let s=game();s.nobles=['noble-1','noble-8','noble-10'];for(const c of ['green','red','black'])for(const id of D.cards.filter(x=>x.bonus===c).slice(0,4).map(x=>x.id))grant(s,id);s=E.apply(s,{type:'take',tokens:{white:1,blue:1,black:1}});assert.equal(s.phase,'noble');assert.equal(s.current,0);assert.equal(E.eligible(s).length,3);s=E.apply(s,{type:'noble',id:'noble-8'});assert.equal(s.players[0].nobles.length,1);assert.equal(s.nobles.length,2);assert.equal(s.current,1);E.validate(s);});
test('A single noble visits automatically; tokens alone never qualify',()=>{let s=game();s.nobles=['noble-1','noble-8','noble-10'];give(s,'green',4);give(s,'red',4);assert.equal(E.eligible(s).length,0);s.bank.green+=4;s.bank.red+=4;s.players[0].tokens.green=s.players[0].tokens.red=0;for(const c of ['green','red'])for(const id of D.cards.filter(x=>x.bonus===c).slice(0,4).map(x=>x.id))grant(s,id);s=E.apply(s,{type:'take',tokens:{blue:1,white:1,black:1}});assert.equal(s.players[0].nobles.length,1);assert.equal(s.players[0].nobles[0],'noble-1');});
test('15 points triggers equal-turn final round; fewer cards breaks tie, exact tie shares win',()=>{let s=game();s.nobles=['noble-1','noble-8','noble-10'];for(const c of ['white','blue','green'])grant(s,`${c}-L3-04`);s=E.apply(s,{type:'take',tokens:{white:1,blue:1,black:1}});assert.equal(s.phase,'action');assert.equal(s.finalRound,true);assert.equal(s.current,1);for(const id of ['red-L3-04','black-L3-04','white-L3-01','white-L1-02'])grant(s,id);s=E.apply(s,{type:'take',tokens:{blue:1,white:1,black:1}});assert.equal(s.phase,'ended');assert.equal(E.score(s.players[0]),15);assert.equal(E.score(s.players[1]),15);assert.deepEqual(s.winners,[0]);let t=game();for(let i=0;i<2;i++){t.current=i;for(const id of (i?['red-L3-04','black-L3-04','red-L3-01']:['white-L3-04','blue-L3-04','green-L3-01']))grant(t,id);give(t,'white',1);}t.current=0;t.finalRound=true;t.current=1;t=E.apply(t,{type:'take',tokens:{blue:1,white:1,black:1}});assert.deepEqual(t.winners,[0,1]);});
test('Empty decks do not refill; no illegal pass; save corruption rejected',()=>{const s=game();s.decks[1]=[];const n=E.apply(s,{type:'reserve',id:s.market[1][0]});assert.equal(n.market[1].length,3);assert.throws(()=>E.apply(s,{type:'reserve',level:1}));assert.throws(()=>E.apply(game(),{type:'pass'}));const bad=game();bad.bank.red++;assert.throws(()=>E.validate(bad));});
test('AI choice independent of opponent hidden hand and deck order',()=>{const s=game();const r=E.apply(s,{type:'reserve',level:1});const t=E.clone(r);[t.players[0].reserved[0],t.decks[1][0]]=[t.decks[1][0],t.players[0].reserved[0]];Object.values(t.decks).forEach(d=>d.reverse());assert.deepEqual(AI.choose(r),AI.choose(t));});
test('120 complete AI games: 2–4 players, conserved cards/tokens, valid save at every action',()=>{let longest=0;for(let seed=1;seed<=120;seed++){let s=E.create(Array.from({length:2+seed%3},(_,i)=>({name:'AI'+i,ai:true})),seed),steps=0;while(s.phase!=='ended'&&steps<1000){const a=AI.choose(s);s=E.apply(s,a);E.validate(s);for(const p of s.players)assert.ok(p.reserved.length<=3);if(s.phase!=='return')for(const p of s.players)assert.ok(E.sum(p.tokens)<=10);steps++;}assert.equal(s.phase,'ended',`seed ${seed} did not finish`);assert.ok(s.winners.length);assert.ok(s.players.some(p=>E.score(p)>=15));longest=Math.max(longest,steps);}console.log('  longest game: '+longest+' actions');});
console.log(`${passed} test groups passed.`);
